name: pherregoz
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - ipykernel
  - basemap
  - basemap-data-hires
  - bokeh
  - cartopy
  - cartopy_offlinedata
  - cftime
  - cmocean
  - dask
  - geos
  - gsw
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - scipy
  - xarray
  - zarr
